### ISSUE TITLE
Console Error 'CreatureSpawnEvent'

### ISSUE THREAD

**Issue by EchocallingEarth** [imDaniX/dangerous-caves#3]
An unknown error related to CreatureSpawnEvent to DangerousCaves v2.0.10-9

https://pastebin.com/73JYHccw

Reporting as Update would not affect this as the recent update was for the structure issue.

This error repeats several times. As a result of the errors, we have removed the plugin, for now, pending a fix. We can install updates etc and continue testing as needed to help improve this plugin.

Excited however as this plugin will bring a bunch to the table for our players taking our servers to the next level.

If you require further information please me know. Thank you for your attention to this matter. 

Respectfully
EchocallingEarth
(Owner Friendlyworldserve Network©)

**Comment by Emiel003** [comment]
I've got exactly the same error as @EchocallingEarth 

no problems with the structures but multiple repeated error of "creaturespawnevent" --> see attachment 

I was also instant killed by "hungeringdarkness" this is maybe another bug :/

But I like the plugin and I look forward to a fix!

Regards 
Emiel

![2020-03-21 16_49_47-emiel@smeagol_ ~](https://user-images.githubusercontent.com/62476025/77230610-b5a4d880-6b95-11ea-8b17-acc9578efc7a.png)

**Comment by imDaniX** [comment]
Please check latest build. Seems like the problem was caused by compile error when I was commiting multiple changes.

> I was also instant killed by "hungeringdarkness" this is maybe another bug :/
It's not a bug. You can configure its damage.
