### ISSUE TITLE
Plugin replacing blocks outside of caves

### ISSUE THREAD

**Issue by ctran4347** [imDaniX/dangerous-caves#5]
I've noticed that if there is a cave entrance near a player's house or village, blocks outside in the over world will start to get replaced with andesite,mushrooms, buttons, etc.

**Comment by imDaniX** [comment]
That's Caves Aging. It's pretty configurable. Set its chance to 0 to disable the feature or make y-max lower to make it work only underground.

**Comment by ctran4347** [comment]
It seems like changing the chance to 0 results to the console spamming the following message : "Noooo, it wont enter the if statement, are u sure caveEnts is true?"

**Comment by imDaniX** [comment]
Seems like you're using not DangerousCaves2. Please note that VeryDangerousCaves and DangerousCaves2 are different things. I don't work on VeryDangerous project.
