### ISSUE TITLE
Elite Mobs conflict

### ISSUE THREAD

**Issue by KillZone** [imDaniX/dangerous-caves#6]
Since the rewrite, if a special mob spawned by your plugin becomes an Elite it may become invulnerable. 
No error message in the server log.

Could you fix this issue?
Plugin version v2.0.15
Elite Mobs 7.1.11

**Comment by imDaniX** [comment]
Please see "Strict spawning rules mode for better compatibility with other plugins" in EliteMobs configuration file.
